blocked-items:
  - AIR
  - CAVE_AIR
  - VOID_AIR
  - BEDROCK
  - BARRIER
  - COMMAND_BLOCK
  - CHAIN_COMMAND_BLOCK
  - REPEATING_COMMAND_BLOCK
  - STRUCTURE_BLOCK
  - STRUCTURE_VOID
  - JIGSAW
  - LIGHT
  - DEBUG_STICK